version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - strapi
    environment:
      VITE_API_URL: ${VITE_API_URL}
      VITE_API_UPLOAD_URL: ${VITE_API_UPLOAD_URL}
      VITE_API_TOKEN: ${VITE_API_TOKEN}

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "1337:1337"
    networks:
      - strapi
    environment:
      DATABASE_CLIENT: sqlite
      DATABASE_FILENAME: .tmp/data.db
      JWT_SECRET: ${JWT_SECRET}
      STRIPE_KEY: ${STRIPE_KEY}
      CLIENT_URL: ${CLIENT_URL}
networks:
  strapi:
